---
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true

env:
  amd: true
  browser: true
  es6: true
  jquery: true
  node: true
  jest: true

plugins:
 - react

extends:
 - airbnb
 - plugin:react/recommended

rules:
  import/extensions:
    - off
    - never